spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2/testdb
    username: postgres
    password: secret
    # initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
